version: 2
jobs:
  checkout:
    resource_class: small  # 1 vCPU 2GB RAM
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    docker:
      - image: quay.io/buildah/stable
    resource_class: dct-local/dct-local
    steps:
      - run:
          name: Build Docker Image
          command: |
            export VERSION=`date +%Y%m%d-%H%M%S -u`

            echo $PASS | docker login -u $USER --password-stdin

            docker build  -f ubuntu-aws.dockerfile       -t kaktooss/aws       -t kaktooss/aws:${VERSION} .
            docker build  -f ubuntu-aws-java.dockerfile  -t kaktooss/aws-java  -t kaktooss/aws-java:${VERSION} .

            docker push kaktooss/aws:${VERSION}
            docker push kaktooss/aws:latest

            docker push kaktooss/aws-java:${VERSION}
            docker push kaktooss/aws-java:latest


workflows:
  version: 2

  build-image:
    jobs:
      - checkout
      - build:
          context: dockerhub
          pre-steps:
            - attach_workspace:
              at: .
          filters:
            branches:
              only:
                - master
