version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            export VERSION=`date +%Y%m%d-%H%M%S -u`

            echo $PASS | docker login -u $USER --password-stdin

            docker build  -f ubuntu-aws.dockerfile       -t kaktooss/aws       -t kaktooss/aws:${VERSION} .
            docker build  -f ubuntu-aws-java.dockerfile  -t kaktooss/aws-java  -t kaktooss/aws-java:${VERSION} .

            docker push kaktooss/aws:${VERSION}
            docker push kaktooss/aws:latest

            docker push kaktooss/aws-java:${VERSION}
            docker push kaktooss/aws-java:latest


workflows:
  version: 2

  build-image:
    jobs:
      - build:
          context: dockerhub
          filters:
            branches:
              only:
                - master
