version: 2

jobs:
  checkout:
    resource_class: dct-local/dct-local
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    environment:
      STORAGE_DRIVER: vfs
      BUILDAH_ISOLATION: chroot
    docker:
      - image: quay.io/buildah/stable
    resource_class: dct-local/dct-local
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Docker Image
          command: |
            export VERSION=`date +%Y%m%d-%H%M%S -u`
            
            echo $PASS | buildah login -u $USER --password-stdin docker.io
            
            buildah bud -t docker.io/kaktooss/aws:${VERSION} -f ubuntu-aws.dockerfile .
            buildah push docker.io/kaktooss/aws:${VERSION}

workflows:
  version: 2

  build-image:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
          context: dockerhub
          filters:
            branches:
              only:
                - master
