version: 2.1

executors:
  machine-base:
    machine:
      docker_layer_caching: true
      image: ubuntu-2204:2022.07.1
    resource_class: medium
  docker-base:
    resource_class: small
    docker:
      - image: cimg/base:2022.09
  docker-dct:
    resource_class: dct-local/dct-local
    docker:
      - image: cimg/base:2022.09

jobs:
  checkout:
    executor: docker-dct
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    executor: docker-base
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker Image
          command: |
            export VERSION=`date +%Y%m%d-%H%M%S -u`
            
            echo $PASS | docker login -u $USER --password-stdin docker.io
            
            docker build -t docker.io/kaktooss/aws:${VERSION} -f ubuntu-aws.dockerfile .
            #docker push docker.io/kaktooss/aws:${VERSION}


  build-image-machine:
    executor: machine-base
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Docker Image
          command: |
            export VERSION=`date +%Y%m%d-%H%M%S -u`
            
            echo $PASS | docker login -u $USER --password-stdin docker.io
            
            docker build -t docker.io/kaktooss/aws:${VERSION} -f ubuntu-aws.dockerfile .
            #docker push docker.io/kaktooss/aws:${VERSION}


workflows:
  version: 2

  build-image:
    jobs:
      - checkout
      - build-image-machine:
          context: dockerhub
          requires:
            - checkout
      - build:
          requires:
            - checkout
          context: dockerhub

