version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            echo $PASS | docker login -u $USER --password-stdin
            ./build.sh

workflows:
  version: 2

  build-image:
    jobs:
      - build:
          context: dockerhub
          filters:
            branches:
              only:
                - master
